"""Initial migration

Revision ID: ae9163cce3b5
Revises:
Create Date: 2025-03-15 18:37:12.769563

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae9163cce3b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'user_account', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            'username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            'user_avatar', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            'user_profile', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.Column(
            'user_role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column('create_time', sa.DateTime(), nullable=False),
        sa.Column('update_time', sa.DateTime(), nullable=False),
        sa.Column('is_delete', sa.Boolean(), nullable=True),
        sa.Column(
            'hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
